
# coding: utf-8

# ---
# 
# _You are currently looking at **version 1.0** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-social-network-analysis/resources/yPcBs) course resource._
# 
# ---

# # Assignment 4

# In[1]:

import networkx as nx
import pandas as pd
import numpy as np
import pickle
get_ipython().magic('matplotlib inline')


# ---
# 
# ## Part 1 - Random Graph Identification
# 
# For the first part of this assignment you will analyze randomly generated graphs and determine which algorithm created them.

# In[2]:

P1_Graphs = pickle.load(open('A4_graphs','rb'))
P1_Graphs


# <br>
# `P1_Graphs` is a list containing 5 networkx graphs. Each of these graphs were generated by one of three possible algorithms:
# * Preferential Attachment (`'PA'`)
# * Small World with low probability of rewiring (`'SW_L'`)
# * Small World with high probability of rewiring (`'SW_H'`)
# 
# Anaylze each of the 5 graphs and determine which of the three algorithms generated the graph.
# 
# *The `graph_identification` function should return a list of length 5 where each element in the list is either `'PA'`, `'SW_L'`, or `'SW_H'`.*

# In[ ]:

#%matplotlib notebook
from collections import Counter
import numpy as np
import matplotlib.pyplot as plt
from random import random

def graph_identification():
    
    # Your Code Here
    for G in P1_Graphs:
        #print(G.nodes(data=True))
        #print(G.edges(data=True))
        print(len(G.nodes()), len(G.edges()))
        d = max([G.degree(n) for n in G.nodes()])
        plt.figure(figsize=(15,15))
        c = random()
        nx.draw_spring(G,  
                     node_color = [(G.degree(n)/float(d), G.degree(n)/float(d), c) for n in G.nodes()], 
                     with_labels = True, 
                     node_size = [2000*G.degree(n)/float(d) for n in G.nodes()],
                     edge_color='lightgray',
                     font_size=6
                  )
        degrees = G.degree()
        labels, values = zip(*Counter(sorted(degrees.values())).items())
        indexes = np.arange(len(labels))
        width = 1
        plt.figure(figsize=(10,10))
        plt.bar(indexes, values, width)
        plt.xticks(indexes + width * 0.5, labels)
        plt.show()

    return ['PA', 'SW_L', 'SW_H', 'PA', 'SW_H'] # Your Answer Here
graph_identification()


# ---
# 
# ## Part 2 - Company Emails
# 
# For the second part of this assignment you will be workking with a company's email network where each node corresponds to a person at the company, and each edge indicates that at least one email has been sent between two people.
# 
# The network also contains the node attributes `Department` and `ManagmentSalary`.
# 
# `Department` indicates the department in the company which the person belongs to, and `ManagmentSalary` indicates whether that person is receiving a managment position salary.

# In[2]:

import matplotlib.pyplot as plt
G = nx.read_gpickle('email_prediction.txt')

print(nx.info(G))
d = max([G.degree(n) for n in G.nodes()])
plt.figure(figsize=(15,15))
nx.draw_random(G,  
             node_color = [(G.degree(n)/float(d), 0.6, G.degree(n)/float(d)) for n in G.nodes()], 
             with_labels = True, 
             node_size = [5000*G.degree(n)/float(d) for n in G.nodes()],
             edge_color = 'lightgray',
             font_size=10
          )


# ### Part 2A - Salary Prediction
# 
# Using network `G`, identify the people in the network with missing values for the node attribute `ManagementSalary` and predict whether or not these individuals are receiving a managment position salary.
# 
# To accomplish this, you will need to create a matrix of node features using networkx, train a sklearn classifier on nodes that have `ManagementSalary` data, and predict a probability of the node receiving a managment salary for nodes where `ManagementSalary` is missing.
# 
# 
# 
# Your predictions will need to be given as the probability that the corresponding employee is receiving a managment position salary.
# 
# The evaluation metric for this assignment is the Area Under the ROC Curve (AUC).
# 
# Your grade will be based on the AUC score computed for your classifier. A model which with an AUC of 0.75 or higher will receive full points.
# 
# Using your trained classifier, return a series of length 252 with the data being the probability of receiving managment salary, and the index being the node id.
# 
#     Example:
#     
#         1       1.0
#         2       0.0
#         5       0.8
#         8       1.0
#             ...
#         996     0.7
#         1000    0.5
#         1001    0.0
#         Length: 252, dtype: float64

# In[24]:

def salary_predictions():
    
    # Your Code Here
    from sklearn.ensemble import RandomForestClassifier 
    from sklearn.svm import SVC
    from sklearn import metrics
    #print(G.nodes(data=True))
    df = pd.DataFrame(index=G.nodes())
    df['Department'] = pd.Series(nx.get_node_attributes(G, 'Department'))
    df['ManagementSalary'] = pd.Series(nx.get_node_attributes(G, 'ManagementSalary'))
    df['clustering'] = pd.Series(nx.clustering(G))
    df['degree'] = pd.Series(G.degree())
    #print(df.head())
    training = df[df['ManagementSalary'].notnull()]
    training['ManagementSalary'] = training['ManagementSalary'].astype(int)
    test = df[df['ManagementSalary'].isnull()]
    #print(training.head())
    #print(test.head())
    Xtrain, ytrain = training[['Department', 'clustering', 'degree']], training['ManagementSalary']
    Xtest = test[['Department', 'clustering', 'degree']]
    #print(Xtest.head())
    #clf = RandomForestClassifier(max_depth=2, random_state=0)
    clf = RandomForestClassifier(random_state=0)
    #clf = SVC(probability=True)
    clf.fit(Xtrain, ytrain)
    ytest = clf.predict_proba(Xtest)
    #ypred = clf.predict_proba(Xtrain)
    #fpr, tpr, thresholds = metrics.roc_curve(ytrain, ypred[:,1], pos_label=1)
    #print(metrics.auc(fpr, tpr))
    return pd.Series(ytest[:,1], index=Xtest.index) # Your Answer Here
#salary_predictions()


# In[30]:

#print(G.nodes(data=True))
df = pd.DataFrame(index=G.nodes())
df['Department'] = pd.Series(nx.get_node_attributes(G, 'Department'))
df['ManagementSalary'] = pd.Series(nx.get_node_attributes(G, 'ManagementSalary'))
df['clustering'] = pd.Series(nx.clustering(G))
df['degree'] = pd.Series(G.degree())
df.head(10)


# In[31]:

training = df[df['ManagementSalary'].notnull()]
training['ManagementSalary'] = training['ManagementSalary'].astype(int)
test = df[df['ManagementSalary'].isnull()]
Xtrain, ytrain = training[['Department', 'clustering', 'degree']], training['ManagementSalary']
Xtest = test[['Department', 'clustering', 'degree']]
from sklearn.model_selection import train_test_split
Xtrain, Xvalid, ytrain, yvalid = train_test_split(Xtrain, ytrain, test_size=0.33, random_state=42)
pd.concat([Xtrain, ytrain], axis=1).head(20)


# In[32]:

pd.concat([Xvalid, yvalid], axis=1).head(20)


# In[33]:

Xtest.head(10)


# In[34]:

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier 
from sklearn.svm import SVC
from sklearn import metrics
from sklearn import metrics
import numpy as np
import matplotlib.pyplot as plt

#print(Xtest.head())
#clf = RandomForestClassifier(max_depth=2, random_state=0)
clf = RandomForestClassifier(random_state=0)
clf2 = SVC(probability=True)
clf3 = GradientBoostingClassifier(random_state=0)
clf.fit(Xtrain, ytrain)
clf2.fit(Xtrain, ytrain)
clf3.fit(Xtrain, ytrain)
ytest = clf.predict_proba(Xtest)
ypred = clf.predict_proba(Xvalid)
ypred2 = clf2.predict_proba(Xvalid)
ypred3 = clf3.predict_proba(Xvalid)
fpr, tpr, thresholds = metrics.roc_curve(yvalid, ypred[:,1], pos_label=1)
print(metrics.auc(fpr, tpr))
auc = metrics.roc_auc_score(yvalid, ypred[:,1])
plt.figure(figsize=(10,10)).clf()
plt.plot(fpr,tpr,label="RandomForest, AUC="+str(auc))
fpr, tpr, thresholds = metrics.roc_curve(yvalid, ypred2[:,1], pos_label=1)
print(metrics.auc(fpr, tpr))
auc = metrics.roc_auc_score(yvalid, ypred2[:,1])
plt.plot(fpr,tpr,label="SVC, AUC="+str(auc))
fpr, tpr, thresholds = metrics.roc_curve(yvalid, ypred3[:,1], pos_label=1)
print(metrics.auc(fpr, tpr))
auc = metrics.roc_auc_score(yvalid, ypred3[:,1])
plt.plot(fpr,tpr,label="GradientBoosting, AUC="+str(auc))
plt.legend(loc=0)


# In[10]:

pd.DataFrame(ytest).head(20)


# In[ ]:

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
print(df.max(), df.min())
#print(Xtest.columns.values)
x, y, z = np.meshgrid(np.linspace(0,42,30).astype(int), np.linspace(0.,1.,30), np.linspace(1,348,30).astype(int), sparse=False, indexing='ij')
#for i in range(10):
#    for j in range(10):
#        for k in range(10):
#            clf.predict(Xtest)
#            xtest = pd.DataFrame([[x[i,j,k], y[i,j,k], z[i,j,k]]], columns=Xtest.columns.values)
#            ytest = clf.predict(xtest)
#            #print(xtest, ytest)
#            ax.scatter(x[i,j,k], y[i,j,k], z[i,j,k], c=('r' if ytest==1. else 'b'), marker=('+' if ytest==1. else 'o'))
Xtest = np.array([x, y, z]).reshape(3, -1).T
ytest = clf.predict(Xtest)
#ytest = clf.predict_proba(Xtest)[:,1]
cm = plt.cm.get_cmap('inferno') #('seismic')
sc = ax.scatter(Xtest[:,0], Xtest[:,1], Xtest[:,2], c=ytest, s=35, cmap=cm)#, marker=np.array(['x' if y==1. else 'o' for y in ytest])
#ax.set_xlim([0, 41])
#ax.set_ylim([0, 1])
#ax.set_zlim([1, 347])
ax.set_xlabel('Department')
ax.set_ylabel('Clustering')
ax.set_zlabel('Degree')
plt.colorbar(sc)
plt.show()


# ### Part 2B - New Connections Prediction
# 
# For the last part of this assignment, you will predict future connections between employees of the network. The future connections information has been loaded into the variable `future_connections`. The index is a tuple indicating a pair of nodes that currently do not have a connection, and the `Future Connection` column indicates if an edge between those two nodes will exist in the future, where a value of 1.0 indicates a future connection.

# In[4]:

future_connections = pd.read_csv('Future_Connections.csv', index_col=0, converters={0: eval})
future_connections.head(10)


# Using network `G` and `future_connections`, identify the edges in `future_connections` with missing values and predict whether or not these edges will have a future connection.
# 
# To accomplish this, you will need to create a matrix of features for the edges found in `future_connections` using networkx, train a sklearn classifier on those edges in `future_connections` that have `Future Connection` data, and predict a probability of the edge being a future connection for those edges in `future_connections` where `Future Connection` is missing.
# 
# 
# 
# Your predictions will need to be given as the probability of the corresponding edge being a future connection.
# 
# The evaluation metric for this assignment is the Area Under the ROC Curve (AUC).
# 
# Your grade will be based on the AUC score computed for your classifier. A model which with an AUC of 0.75 or higher will receive full points.
# 
# Using your trained classifier, return a series of length 122112 with the data being the probability of the edge being a future connection, and the index being the edge as represented by a tuple of nodes.
# 
#     Example:
#     
#         (107, 348)    0.35
#         (542, 751)    0.40
#         (20, 426)     0.55
#         (50, 989)     0.35
#                   ...
#         (939, 940)    0.15
#         (555, 905)    0.35
#         (75, 101)     0.65
#         Length: 122112, dtype: float64

# In[25]:

def new_connections_predictions():
    
    # Your Code Here
    #print(G.edges(data=True))
    from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier 
    from sklearn.svm import SVC
    from sklearn import metrics
    future_connections['preferential attachment'] = [i[2] for i in nx.preferential_attachment(G, future_connections.index)]
    future_connections['Common Neighbors'] = future_connections.index.map(lambda e: len(list(nx.common_neighbors(G, e[0], e[1]))))    
    #print(future_connections.head())
    training = future_connections[~future_connections['Future Connection'].isnull()]
    training['Future Connection'] = training['Future Connection'].astype(int)
    test = future_connections[future_connections['Future Connection'].isnull()]
    #print(training.head())
    #print(test.head())
    Xtrain, ytrain = training[['preferential attachment', 'Common Neighbors']], training['Future Connection']
    Xtest = test[['preferential attachment', 'Common Neighbors']]
    #print(Xtest.head())
    #clf = RandomForestClassifier(max_depth=2, random_state=0)
    #clf = RandomForestClassifier(random_state=0)
    clf = GradientBoostingClassifier()
    #clf = SVC(probability=True)
    clf.fit(Xtrain, ytrain)
    ytest = clf.predict_proba(Xtest)
    #ypred = clf.predict_proba(Xtrain)
    #fpr, tpr, thresholds = metrics.roc_curve(ytrain, ypred[:,1], pos_label=1)
    #print(metrics.auc(fpr, tpr))
    return pd.Series(ytest[:,1], index=Xtest.index) # Your Answer Here
#new_connections_predictions()


# In[5]:

future_connections['preferential attachment'] = [i[2] for i in nx.preferential_attachment(G, future_connections.index)]
future_connections['Common Neighbors'] = future_connections.index.map(lambda e: len(list(nx.common_neighbors(G, e[0], e[1])))) 
future_connections.head(20)


# In[6]:

training = future_connections[~future_connections['Future Connection'].isnull()]
training['Future Connection'] = training['Future Connection'].astype(int)
test = future_connections[future_connections['Future Connection'].isnull()]
#print(training.head())
#print(test.head())
Xtrain, ytrain = training[['preferential attachment', 'Common Neighbors']], training['Future Connection']
Xtest = test[['preferential attachment', 'Common Neighbors']]
from sklearn.model_selection import train_test_split
Xtrain, Xvalid, ytrain, yvalid = train_test_split(Xtrain, ytrain, test_size=0.33, random_state=42)
pd.concat([Xtrain, ytrain], axis=1).head(20)    


# In[7]:

pd.concat([Xvalid, yvalid], axis=1).head(20)


# In[8]:

Xtest.head(10)


# In[9]:

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier 
from sklearn.svm import SVC
from sklearn import metrics
import numpy as np
import matplotlib.pyplot as plt

#print(Xtest.head())
#clf = RandomForestClassifier(max_depth=2, random_state=0)
clf = RandomForestClassifier(random_state=0)
#clf2 = SVC(probability=True)
clf3 = GradientBoostingClassifier(random_state=0)
clf.fit(Xtrain, ytrain)
#clf2.fit(Xtrain, ytrain)
clf3.fit(Xtrain, ytrain)
ytest = clf.predict_proba(Xtest)
ypred = clf.predict_proba(Xvalid)
#ypred2 = clf2.predict_proba(Xvalid)
ypred3 = clf3.predict_proba(Xvalid)
fpr, tpr, thresholds = metrics.roc_curve(yvalid, ypred[:,1], pos_label=1)
print(metrics.auc(fpr, tpr))
auc = metrics.roc_auc_score(yvalid, ypred[:,1])
plt.figure(figsize=(10,10)).clf()
plt.plot(fpr,tpr,label="RandomForest, AUC="+str(auc))
#fpr, tpr, thresholds = metrics.roc_curve(yvalid, ypred2[:,1], pos_label=1)
#print(metrics.auc(fpr, tpr))
#auc = metrics.roc_auc_score(yvalid, ypred2[:,1])
#plt.plot(fpr,tpr,label="SVC, AUC="+str(auc))
fpr, tpr, thresholds = metrics.roc_curve(yvalid, ypred3[:,1], pos_label=1)
print(metrics.auc(fpr, tpr))
auc = metrics.roc_auc_score(yvalid, ypred3[:,1])
plt.plot(fpr,tpr,label="GradientBoosting, AUC="+str(auc))
plt.legend(loc=0)


# In[22]:

import matplotlib.pyplot as plt
import numpy as np
fig = plt.figure()#figsize=(10,10))
print(future_connections.max(), future_connections.min())
x, y = np.meshgrid(np.linspace(1,10000,200).astype(int), np.linspace(0,29,200), sparse=False, indexing='ij')
Xtest = np.array([x, y]).reshape(2, -1).T
#ytest = clf.predict(Xtest)
ytest = clf.predict_proba(Xtest)[:,1]
cm = plt.cm.get_cmap('RdYlBu')
sc = plt.scatter(Xtest[:,0], Xtest[:,1], c=ytest, s=35, cmap=cm)#, marker=np.array(['x' if y==1. else 'o' for y in ytest])
plt.xlabel('Preferential attachment')
plt.ylabel('Common Neighbors')
plt.colorbar(sc)
plt.show()


# In[24]:

import matplotlib.pyplot as plt
import numpy as np
fig = plt.figure()#figsize=(10,10))
print(future_connections.max(), future_connections.min())
x, y = np.meshgrid(np.linspace(1,10000,200).astype(int), np.linspace(0,29,200), sparse=False, indexing='ij')
Xtest = np.array([x, y]).reshape(2, -1).T
ytest = clf.predict(Xtest)
#ytest = clf.predict_proba(Xtest)[:,1]
cm = plt.cm.get_cmap('RdYlBu')
sc = plt.scatter(Xtest[:,0], Xtest[:,1], c=ytest, s=35, cmap=cm)#, marker=np.array(['x' if y==1. else 'o' for y in ytest])
plt.xlabel('Preferential attachment')
plt.ylabel('Common Neighbors')
plt.title('Decision Boundary learnt for Link Prediction with RandomForest Classifier')
plt.colorbar(sc)
plt.show()


# In[ ]:



