# openai.api_key='xxxxxx'

import os
import openai
import secret
# openai.api_key='xxxxxx'

# WRITE YOUR CODE HERE
prompts ="Write a tagline for an ice cream shop"
response = openai.Completion.create(model="text-davinci-002", 
                                    prompt=prompts)

print(response['choices'][0]['text'].strip())

'''
{
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "Animal behavior can vary greatly depending on the species and environment they inhabit.",
        "role": "assistant"
      }
    }
  ],
  "created": 1681688074,
  "id": "chatcmpl-766B8BCz36OIR7eLKRFVbIoGO8qgL",
  "model": "gpt-3.5-turbo-0301",
  "object": "chat.completion",
  "usage": {
    "completion_tokens": 14,
    "prompt_tokens": 31,
    "total_tokens": 45
  }
}
'''

import os
import openai
import secret
# openai.api_key='xxxxxx'
# WRITE YOUR CODE HERE
response=openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "What's a good book to read on a rainy day?"}
    ],
  n=3
)

print(response)

for i in (response["choices"]):
  print(i["message"]['content'].strip()) 
  print(" ////////  ")
  
import os
import openai
import secret
# openai.api_key='xxxxxx'

# WRITE YOUR CODE HERE
response = openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "What's a good book to read on a rainy day?"}
    ],
  max_tokens = 25,
  temperature = 1,
  n = 6
)

for i in (response["choices"]):
  print(i["message"]['content'].strip()) 
  print(" ////////  ")

# WRITE YOUR CODE HERE
import os
import openai
import secret
# openai.api_key='xxxxxx'

response=openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a financial advisor."},
        {"role": "user", "content": "What are some tips for saving money?"},
        {"role": "assistant", "content": "Creating a budget, reducing expenses, and saving on utilities are some ways to save money."},
        {"role": "user", "content": "How do I create a budget?"}
    ]
)

print(response['choices'][0]['message']['content'])

response=openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
            {"role": "system", "content": "You are a travel expert specializing in European destinations."},
            {"role":"user","content": "Give me the top 2 tourist destinations in Germany for my honeymoon." }
    ]
)

{"role": "system", "content": "You are a helpful assistant."}, 
 {"role": "user", "content": "What is the best way to cook it?"},  
{"role": "assistant", "content": "I need more information to provide a specific answer. What ingredient or dish are you referring to?"}  
 
response=openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "What's a good book to read on a rainy day?"}
    ],
  n=3,
  temperature=0.7
)

from typing import List
import os
import openai
import secret

# openai.api_key='xxxxxx'

def chatfunctions(prompts: List[str], temp: float, max_t: int) -> List[str]:
  # WRITE YOUR CODE HERE
  responses = []
  for prompt in prompts:
    response=openai.ChatCompletion.create(
      model="gpt-3.5-turbo",
      messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ],
      max_tokens = max_t,
      temperature = temp,
      n=1
    )
    #print(response)
    responses.append(response['choices'][0]['message']['content'].strip())
  return responses

def user_experience(prompt: str, temp: float, max_t: int):
    response = chatfunctions([prompt], temp, max_t)[0]
    print(f'# User: {prompt}')
    print(f'# AI: {response}')

# Example 1:
# prompts = ["What is the capital of France?", "Who is Elon Musk?", "What is the weather like?"]
# print(chatfunctions(prompts, 0.5, 100))
# The output should be a list of three responses generated by the AI model.

# Example 2:
# user_experience("What is the capital of France?", 0.5, 100)
# The console should display a user-friendly conversation, for example:
# User: What is the capital of France?
# AI: The capital of France is Paris.

# Example 3:
# prompts = ["What is AI?", "What are some applications of AI?"]
# print(chatfunctions(prompts, 0.7, 150))
# The output should be a list of two responses generated by the AI model.

# Example 4:
# user_experience("What is AI?", 0.7, 150)
# The console should display a user-friendly conversation, for example:
# User: What is AI?
# AI: AI, or Artificial Intelligence, refers to the simulation of human intelligence processes by machines, especially computer systems. This includes learning, reasoning, problem-solving, perception, and language understanding.


import os
import openai
import secret
# openai.api_key='xxxxxx'
# WRITE YOUR CODE HERE

response=openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a coding assistant with expertise in Python."},
        {"role": "user", "content": "Write a Python function to find the factorial of a given number using recursion."}
    ]
)

print(response['choices'][0]['message']['content'].strip())


import os
import openai
import secret
# openai.api_key='xxxxxx'

message=[
        {"role": "system", "content": "You are a coding assistant with expertise in JavaScript."},
        {"role": "user", "content": "I have this JavaScript code: `function add(a, b) { return a + b; }`. Can you suggest any improvements or optimizations?"}
    ]
# FREEZE CODE BEGIN
response=openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages= message
)

print(response['choices'][0]['message']['content'].strip())

# FREEZE CODE END

'''
The code you have shared is already concise and efficient. However, here are a few suggestions for optimization:

1. Use strict equality (`===`) instead of loose equality (`==`) when comparing values. This helps avoid unexpected type coercion. For example, `1 == '1'` returns `true`, but `1 === '1'` returns `false`.

2. Consider adding type checks or validations at the beginning of the function to ensure the inputs are of the expected types. This can help prevent unexpected errors. For example, you can add a check to ensure both `a` and `b` are numbers before performing addition.

   ```javascript
   function add(a, b) {
     if (typeof a !== 'number' || typeof b !== 'number') {
       throw new Error('Both arguments must be numbers.');
     }
     return a + b;
   }
   ```

3. If you are working with very large numbers or need to handle decimal precision, consider using the `BigInt` or `Decimal` data types respectively, instead of regular numbers.

These optimizations may not be necessary depending on the specific use case, but they can improve code reliability and maintainability.
'''

import os
import openai
import secret
# openai.api_key='xxxxxx'

message=[ 
{"role": "system", "content": "You are a coding assistant with expertise in Python."},
{"role": "user", "content": "Explain the following Python code: `def square(x): return x * x`"}
    ]

# FREEZE CODE BEGIN
response=openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages= message
)

print(response['choices'][0]['message']['content'].strip())

# FREEZE CODE END

message = {"role": "system", "content": "You are a coding assistant with expertise in Python."},
{"role": "user", "content": "I have this Python code that throws an IndexError: `def get_element(lst, index): return lst[index]`. Can you help me understand the issue and suggest a fix?"}

message = [
  {"role": "system", "content": "You are a coding assistant with expertise in Python."},
        {"role": "user", "content": "What are some best practices for naming variables and functions in Python?"}
    ]

message =[
        {"role": "system", "content": "You are a coding assistant with expertise in JavaScript."},
        {"role": "user", "content": "I have this JavaScript code: `function add(a, b) { return a + b; }`. Can you suggest any improvements or optimizations?"}
    ]

	
### FREEZE CODE BEGIN
import openai
import os

# openai.api_key='xxxxxx'
# WRITE YOUR CODE HERE

response=openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a coding assistant with expertise in Python."},
        {"role": "user", "content": "Write a Python function to reverse a given input string."}
    ]
)

print(response['choices'][0]['message']['content'].strip())


# WRITE YOUR CODE HERE
import openai
import os

# openai.api_key='xxxxxx'
message=[{"role": "system", "content": "You are a collaborative programming assistant with expertise in Python."},
        {"role": "user", "content": "Alice: I'm having trouble understanding how to use Python decorators. Can you explain them to me?"},
        {"role": "user", "content": "Bob: I think I understand decorators, but I could use some help with a specific example. Can you provide one?"}
    ]

response=openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages= message
)
print(response['choices'][0]['message']['content'].strip())

'''
Alice: Sure! I'd be happy to explain decorators to you. In Python, a decorator is a way to modify or enhance the functionality of an existing function by wrapping it with additional code. Decorators allow you to add functionality to a function without directly modifying its code.

Bob: That makes sense, but how exactly do decorators work?

Alice: At a high level, decorators work by taking a function as input, modifying it in some way, and returning the modified function. This is often referred to as "wrapping" the original function. Decorators make use of a special syntax using the '@' symbol, which is placed above the function definition.

Bob: Could you provide an example to help illustrate this?

Alice: Sure! Let's say we have a simple function that adds two numbers together:

```python
def add_numbers(a, b):
    return a + b
```

Now, let's say we want to add some additional functionality to this function, like logging the arguments and the return value every time it is called. We can use a decorator to achieve this:

```python
def log_function(func):
    def wrapper(*args, **kwargs):
        print(f"Calling function '{func.__name__}' with arguments: {args}, {kwargs}")
        result = func(*args, **kwargs)
        print(f"Function returned: {result}")
        return result
    return wrapper

@log_function
def add_numbers(a, b):
    return a + b
```

In this example, the `log_function` decorator takes the `add_numbers` function as input and returns a modified function called `wrapper`. The `wrapper` function logs the function call and the return value, and then calls the original `add_numbers` function.

Bob: That's really helpful! So by using the `@log_function` syntax, the `add_numbers` function now includes the additional logging behavior?

Alice: Exactly! When you use the `@log_function` syntax above a function definition, it is equivalent to calling `add_numbers = log_function(add_numbers)`. The `add_numbers` function gets replaced with the modified version that includes the logging behavior.

Bob: That's a great explanation, Alice! I think I finally understand decorators now. Thank you!

Alice: You're welcome, Bob! I'm glad I could help. Don't hesitate to ask if you have any further questions.
'''

message = [{"role": "system", "content": "You are a collaborative programming assistant with expertise in Python."},
        {"role": "assistant", "content": "What are some key challenges you've faced while working on this Python project, and how have you addressed them? Share your experiences and any potential solutions."}
    ]
message = [{"role": "system", "content": "You are a collaborative programming assistant with expertise in Python."},
        {"role": "assistant", "content": "We're currently working with list comprehensions in Python. Can you share an example of a challenging list comprehension you've come across and how you approached solving it? Feel free to discuss any alternative solutions you considered."}
    ]

message = [{"role": "system", "content": "You are a collaborative programming assistant with expertise in Python."},
        {"role": "assistant", "content": "Here's a Python function we've been working on:\n\n```python\ndef calculate_area(width, height):\n    return width * height\n```\n\nCould you please review this function and provide any suggestions for improvement or optimization? Feel free to discuss any potential issues or alternative approaches."}
    ]

message = [
        {"role": "system", "content": "You are a collaborative programming assistant with expertise in Python."},
        {"role": "assistant", "content": "We have a Python function that processes a large dataset, but its performance is not satisfactory. Let's brainstorm some ideas to optimize the function. Here are some initial suggestions:\n\n1. Use vectorized operations with libraries like NumPy.\n2. Apply parallel processing techniques using the multiprocessing module. \nPlease share your thoughts on these ideas, and feel free to suggest additional approaches."}
    ]

message = [
        {"role": "system", "content": "You are a collaborative programming assistant with expertise in Python."},
        {"role": "assistant", "content": "We have a Python function that processes a large dataset, but its performance is not satisfactory. Let's brainstorm some ideas to optimize the function. Here are some initial suggestions:\n\n1. Use vectorized operations with libraries like NumPy.\n2. Apply parallel processing techniques using the multiprocessing module.\n3. Profile the code to identify performance bottlenecks and optimize them.\n4. Consider using a more efficient data structure or algorithm.\n\nPlease share your thoughts on these ideas, and feel free to suggest additional approaches."}
    ]

message = [
        {"role": "system", "content": "You are a collaborative assistant with expertise in web development and user experience."},
        {"role": "assistant", "content": "Our team is working on a web application, and we want to improve the user experience. Can you generate some ideas to enhance the UX of our application?"}
    ]
	
import os
import openai
import secret

# openai.api_key='xxxxxx'
# WRITE YOUR CODE HERE

def collaborative_chat_gpt(prompt: str) -> str:
    message = [
        {"role": "system", "content": "You are a knowledgeable assistant."},
        {"role": "user", "content": prompt}
    ]
    response=openai.ChatCompletion.create(
      model="gpt-3.5-turbo",
      messages = message)

    return response['choices'][0]['message']['content'].strip()

print(collaborative_chat_gpt("What is the capital of France?"))


import os
import openai
import secret
# openai.api_key='xxxxxx'
# WRITE YOUR CODE HERE

def chatgpt_code_review(file_path):
  with open(file_path, 'r') as file:
    code = file.read()
    message = [{"role": "system", "content": "You are a collaborative programming assistant with expertise in Python."},
          {"role": "assistant", "content": f"Here's a Python code we've been working on, install the required libraries before runnign the code :\n\n```python\n{code}\n```\n\nCould you please review this code and provide any suggestions for improvement or optimization? Feel free to discuss any potential issues or alternative approaches."}
      ]
    response=openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages = message)

    return response['choices'][0]['message']['content'].strip()

print(chatgpt_code_review("temp_copy.py"))

'''
# temp_copy.py
import os
import openai
import secret
openai.api_key=secret.api_key



response=openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
            {"role": "system", "content": "You are a travel expert specializing in European destinations."},
            {"role":"user","content": "Give me the top 2 tourist destinations in Germany for my honeymoon." }
    ]
)

print(response['choices'][0]['message']['content'])

'''

'''
The code you provided seems fine, but there are a few things you could consider for improvement:

1. Handling exceptions: It's important to handle any exceptions that might occur during API calls or other operations. This will help your code to gracefully handle errors and avoid unexpected crashes. You can use try-except blocks to catch exceptions and handle them appropriately.

2. Input validation: You might want to add some input validation to ensure that the user provides valid input. For example, you can check if the user input is non-empty before making the API call.

3. Structure the code in functions: It's a good practice to wrap your code inside functions, as it promotes modularity and reusability. You can create a function that takes the user input as a parameter and returns the response from the API. This will make your code easier to adapt and test in different scenarios.

4. Use environment variables for sensitive information: Rather than hardcoding sensitive information (like API keys) directly into the code, it's recommended to use environment variables. This helps to keep your sensitive information secure, especially when sharing or version-controlling your code.

5. Code documentation: Adding comments to your code will make it easier for other developers (including yourself in the future) to understand the purpose and functionality of each part of the code.

Here's an example incorporating these suggestions:

```python
import os
import openai
from dotenv import load_dotenv

# Load API key from environment variable
load_dotenv()
API_KEY = os.getenv("OPENAI_API_KEY")
openai.api_key = API_KEY


def get_top_destinations(question):
    try:
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a travel expert specializing in European destinations."},
                {"role":"user","content": question }
            ]
        )
        
        return response['choices'][0]['message']['content']
    
    except openai.error.APIError as e:
        print(f"An API error occurred: {str(e)}")
        return None


if __name__ == "__main__":
    user_input = input("Enter your question: ")
    if user_input:
        response = get_top_destinations(user_input)
        if response:
            print(response)
        else:
            print("Failed to fetch response.")
    else:
        print("Invalid input.")
```

Please note that in this example, I have used the `python-dotenv` package to load the API key from an environment variable. You can install it using `pip install python-dotenv`.
'''

import os
import openai
import secret
# openai.api_key='xxxxxx'
# WRITE YOUR CODE HERE

response=openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "What's a good book to read on a rainy day? please just name 2."}
    ],
  n=3
)

for i in (response["choices"]):
  print(i["message"]['content'].strip()) 
  print(" ////////    ")
  
  
prompts = ["Who won the world series in 2020?", "What's the capital of France?", "Who wrote Pride and Prejudice?"]
responses = Generate(prompts)

for i, (response, time_taken) in enumerate(responses):
    print(f"Prompt: {prompts[i]}\nResponse: {response}\nTime Taken: {time_taken} seconds\n")
	
'''
Prompt: Who won the world series in 2020?
Response: The Los Angeles Dodgers won the World Series in 2020.
Time Taken: 1.0225541591644287 seconds

Prompt: What's the capital of France?
Response: The capital of France is Paris.
Time Taken: 0.6920163631439209 seconds

Prompt: Who wrote Pride and Prejudice?
Response: Pride and Prejudice was written by Jane Austen.
Time Taken: 1.2438981533050537 seconds
'''

import os
import openai
import secret
import time
# openai.api_key='xxxxxx'
# WRITE YOUR CODE HERE

def Generate(prompts):
  responses = []
  for prompt in prompts:
    # Start the timer
    start_time = time.time()

    # Make the API call to generate the completion
    response=openai.Completion.create(
      engine="text-davinci-002",  # Select the engine
            prompt=prompt,
            max_tokens=100  # Limit the response length
    )

    # Calculate the elapsed time
    elapsed_time = time.time() - start_time
    responses.append((response.choices[0].text.strip(), elapsed_time))
  return responses

prompts = ["Who won the world series in 2020?", "What's the capital of France?", "Who wrote Pride and Prejudice?"]
responses = Generate(prompts)

for i, (response, time_taken) in enumerate(responses):
    print(f"Prompt: {prompts[i]}\nResponse: {response}\nTime Taken: {time_taken} seconds\n")

'''
Prompt: Who won the world series in 2020?
Response: The Los Angeles Dodgers won the world series in 2020.
Time Taken: 0.364626407623291 seconds

Prompt: What's the capital of France?
Response: Paris
Time Taken: 0.1741948127746582 seconds

Prompt: Who wrote Pride and Prejudice?
Response: Jane Austen
Time Taken: 0.197035551071167 seconds
'''

import os
import openai
# openai.api_key='xxxxxx'
# WRITE YOUR CODE HERE
prompts = [
    "Write a summary of a book about artificial intelligence.",
    "Explain the importance of machine learning in today's world.",
    "Describe the role of neural networks in natural language processing."
]

responses = []

for prompt in prompts:
    response = openai.Completion.create(
        engine="text-davinci-002",
        prompt=prompt,
        max_tokens=50,
        n=1,
        stop=None,
        temperature=0.7
    )
    responses.append(response.choices[0].text.strip())

# Iterate through the prompts and their corresponding responses
for i, (prompt, response) in enumerate(zip(prompts, responses)):
    print(f"Prompt {i + 1}: {prompt}")
    print(f"Response {i + 1}: {response}\n")
	
# Prepare your batch of prompts

prompts = ["who is the oldest president", " what is the name of a famous cave with monsters in greek mythology"]


# Record the start time
start_time = time.time()

# Make the API call
responses = openai.Completion.create(
    engine="text-davinci-002",
    prompt=prompts,
    max_tokens=50,
    n=len(prompts),
    stop=None,
    temperature=0.7
)

# Record the end time
end_time = time.time()

# Calculate response time
response_time = end_time - start_time

print(f"Response time: {response_time} seconds")

num_requests = len(prompts)
throughput = num_requests / response_time

print(f"Throughput: {throughput} requests per second")

usage = responses['usage']
total_tokens = usage['total_tokens']
prompt_tokens = usage['prompt_tokens']
completion_tokens = usage['completion_tokens']

print(f"API Usage:")
print(f"  Total tokens: {total_tokens}")
print(f"  Prompt tokens: {prompt_tokens}")
print(f"  Completion tokens: {completion_tokens}")

error_count = 0

try:
    responses = openai.Completion.create(
        engine="text-davinci-002",
        prompt=prompts,
        max_tokens=50,
        n=len(prompts),
        stop=None,
        temperature=0.7
    )
except Exception as e:
    error_count += 1
    print(f"Error encountered: {e}")

error_rate = error_count / num_requests

print(f"Error rate: {error_rate}")

import time
import openai
import os
# openai.api_key='xxxxxx'

# WRITE YOUR CODE HERE
def GenerateBatch(prompts: list) -> list:

  # Make the API call
  responses = openai.Completion.create(
      engine="text-davinci-002",
      prompt=prompts,
      max_tokens=50,
      n=1,
      stop=None,
      temperature=0.7
  )

  responses_list = []
  for i in range(len(prompts)):
    responses_list.append((responses.choices[i].text.strip(), responses.choices[i].finish_reason))

  return responses_list

print( GenerateBatch(["what is pluto", "how big is sun"]))

'''
# style.css
body {
  font-family: Arial, sans-serif;
}

h1 {
  text-align: center;
}

form {
  max-width: 800px;
  margin: 0 auto;
}

.input-group {
  display: flex;
  flex-direction: column;
  margin-bottom: 10px;
}

label {
  font-weight: bold;
}

textarea {
  height: 100px;
}

#submit-button {
  margin-top: 20px;
}

'''

'''
# app.js
const form = document.getElementById("chat-form");
const userInput = document.getElementById("user-input");
const responseElem = document.getElementById("response");

form.addEventListener("submit", async (event) => {
  event.preventDefault();

  const userInputValue = userInput.value.trim();

  if (!userInputValue) {
    return;
  }

  const response = await fetch("/chat", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ user_input: userInputValue }),
  });

  const responseData = await response.json();

  if (response.ok) {
    const chatResponse = responseData.response;
    responseElem.value = chatResponse;
  } else {
    alert("Error when fetching response from ChatGPT API.");
  }
});
'''