function [BW,maskedImage] = segmentImage(X)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 28-Dec-2022
%----------------------------------------------------


% Threshold image - adaptive threshold
BW = imbinarize(im2gray(X), 'adaptive', 'Sensitivity', 0.390000, 'ForegroundPolarity', 'dark');

% Invert mask
BW = imcomplement(BW);

% Fill holes
BW = imfill(BW, 'holes');

% Fill holes
BW = imfill(BW, 'holes');

% Close mask with default
radius = 25;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

